version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: zumra-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - zumra-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zumra Chat application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zumra-app
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/zumra
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - JWT_EXPIRE=30d
    networks:
      - zumra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx service for serving static files and reverse proxy
  nginx:
    image: nginx:alpine
    container_name: zumra-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - zumra-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  zumra-network:
    driver: bridge

volumes:
  mongodb_data:
