services:
  - type: web
    name: zumra-chat
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://nawafallharthii:GpGhJgA8y5mSNfk8@zumra.baplsoc.mongodb.net/?retryWrites=true&w=majority&appName=Zumra
      - key: JWT_SECRET
        value: zumra_chat_secret_key
      - key: JWT_EXPIRE
        value: 30d
